workspace = { members = ["lib/clauser"] }
[package]
name = "mapzk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clauser = { path = "lib/clauser" }
